### ISSUE TITLE
Occlusion culling working ?

### ISSUE THREAD

**Issue by Shinao** [ellioman/Indirect-Rendering-With-Compute-Shaders#1]
Hi there,

Very interested in this, is it supposed to work or is it a work in progress ?
I have tried this project on Unity 2017.3f but the occlusion culling does not seem to do anything except when the object is out of the camera view, which I don't think is what it's supposed to.

Thanks

**Comment by ellioman** [comment]
Heyhey,

This is still a work in progress but the occlusion culling should be semi-working though. 

The problem is that you currently can not have the scene window open, only the Game window for it to work properly. This is one of the things I'm going to look into very soon, probably next week.

See what happens when you:
* Run the scene without the scene window open anywhere
* Turn on the "Should Display GUI" flag on the "Hi Z Occlusion script" that's attached to the MainCamera.
* Move the camera towards some occluder
* Toggle on and off the "Should Hi Z Cull" on the "Hi Z Occlusion script"

See if you notice a difference in FPS and the numbers shown on the screen :)

**Comment by Shinao** [comment]
Indeed it was the scene view that was messing with the occlusion. It works pretty good now, thanks !
Well I'm excited to see how it gets better :)
